### ISSUE TITLE
Multiple --path options

### ISSUE THREAD

**Issue by rodion-arr** [stechstudio/Laravel-PHP-CS-Fixer#19]
First of all - thanks for the package!

Faced next issue: I'd like to specify 2 project folders (`app` and `tests`) for fixer command using `--path` option.

According to README it supports multiple values:
```
Options:
      --path[=PATH]                    The path. (multiple values allowed)
```

Here is my command:
```bash
php artisan fixer:fix --path app --path tests --dry-run
```

Error in result  `For multiple paths config parameter is required.`:
```
   PhpCsFixer\ConfigurationException\InvalidConfigurationException  : For multiple paths config parameter is required.

  at path_to_project\vendor\friendsofphp\php-cs-fixer\src\Console\ConfigurationResolver.php:582
    578|
    579|         if ($this->isStdIn() || 0 === \count($path)) {
    580|             $configDir = $this->cwd;
    581|         } elseif (1 < \count($path)) {
  > 582|             throw new InvalidConfigurationException('For multiple paths config parameter is required.');
    583|         } elseif (is_file($path[0]) && $dirName = pathinfo($path[0], PATHINFO_DIRNAME)) {
    584|             $configDir = $dirName;
    585|         } else {
    586|             $configDir = $path[0];
```

**So here are questions from my side:**
1. Do we have an example of config file for multiple paths?
2. Do we need to remove `(multiple values allowed)` from `--path` docs?

Thanks in advance!

**Comment by tai-sho** [comment]
I am also interested in this topic.
Is there any way?

**Comment by bubba-h57** [comment]
I'll dig into it and get back to you.

**Comment by bubba-h57** [comment]
I believe all of the issues discussed here are solved in PR https://github.com/stechstudio/Laravel-PHP-CS-Fixer/pull/31 which will be the next major version with support for PHP-CS-Fixer 3.0. If you want to pull that branch and take a look at, I'd appreciate any feedback.

**Comment by rodion-arr** [comment]
Hi, it looks like `--path` option was dropped?

**Comment by bubba-h57** [comment]
Doh, yea ... I moved those to arguments ... but they really should be optional. I'll update that shortly.

**Comment by rodion-arr** [comment]
Ok from my side. I believe my issue can be closed for now.
