### ISSUE TITLE
license violation

### ISSUE THREAD

**Issue by keradus** [stechstudio/Laravel-PHP-CS-Fixer#29]
https://github.com/stechstudio/Laravel-PHP-CS-Fixer/blob/v2.2.0/src/Console/FixCommand.php is almost copy-paste of https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.14.6/src/Console/Command/FixCommand.php , especially the `execute` method.

While it's OK to take benefit of the code, one doing that should respect the [license](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.18/LICENSE) and [copyrights](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.14.6/src/Console/Command/FixCommand.php#L3-L11) - especially the [following](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.18/LICENSE#L11-L12)
> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

right now, this package is [claiming](https://github.com/stechstudio/Laravel-PHP-CS-Fixer/blob/master/LICENSE#L3) full copyrights for this package

**Comment by bubba-h57** [comment]
I remember that now. I copy/pasted it at the time because whomever originally wrote it made the class final and I didn't think much beyond that, I was just frustrated by a final class. I'll fix it, thanks for bringing it to my attention.

**Comment by keradus** [comment]
Thank you - ref https://github.com/stechstudio/Laravel-PHP-CS-Fixer/commit/867d5d3434205be85bd1bfefb3710e7995a53e22 .

For context, the class is internal to the package and was not supposed to be used externally, so it was also marked as final ;)

**Comment by bubba-h57** [comment]
You are most welcome. I **know** why people mark PHP classes as final, I just don't **understand** why people mark PHP classes as final. :-) Thanks again for bringing it to my attention.
