### ISSUE TITLE
Support for the v3.0

### ISSUE THREAD

**Issue by binaryk** [stechstudio/Laravel-PHP-CS-Fixer#30]
Thanks for the package Stech Studio.

Can we have support for the 3.0? 

Thanks!

https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v3.0.0

**Comment by bubba-h57** [comment]
Yes indeed, this is a great idea.

**Comment by bubba-h57** [comment]
Take a look at `composer require stechstudio/laravel-php-cs-fixer:dev-Fixer-3.0-Support` and let me know what you think.

**Comment by ALTELMA** [comment]
Does not have compatibility with Lumen, right?
 I got an error from fixer.php app_path() not found
