### ISSUE TITLE
Laravel-PHP-CS-Fixer with php-cs-fixer in vs-code

### ISSUE THREAD

**Issue by Daespinosag** [stechstudio/Laravel-PHP-CS-Fixer#34]
- Is it possible to integrate with the extension` php-cs-fixer` in `vs-code` so that it formats with the configurations of `Laravel-PHP-CS-Fixer` where a file is saved?

**Comment by TheFrankman** [comment]
+1

**Comment by mxsxs2** [comment]
I know it is a bit late. Anyhow:
I use this in VSCode:
```
"emeraldwalk.runonsave": {
    "commands": [
      {
        "match": "\\.php$",
        "isAsync": false,
        "cmd": "php src/artisan fixer:fix -- ${file}"
      }
    ]
  },
```
  
 With: https://github.com/emeraldwalk/vscode-runonsave

**Comment by bubba-h57** [comment]
Run on save as @mxsxs2 notes is the way to do it.
