### ISSUE TITLE
Argument mismatch for ReportSummary

### ISSUE THREAD

**Issue by ALTELMA** [stechstudio/Laravel-PHP-CS-Fixer#39]
I got this error when running fixer

```sh
 Too few arguments to function PhpCsFixer\Console\Report\FixReport\ReportSummary::__construct(), 6 passed in /var/www/vendor/stechstudio/laravel-php-cs-fixer/src/Services/Fixer/Concerns/HasFixEvent.php on line 25 and exactly 7 expected
```

As I checked, Look like PHP-cs-fixer change something on their side
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/src/Console/Report/FixReport/ReportSummary.php

Could you please update your package to support a new argument?

**Comment by scramatte** [comment]
Same problem here
Please fix it

**Comment by jszobody** [comment]
We'd be happy to review a PR if either of you want to provide one! Otherwise it might be a bit before we have time to get to this.

**Comment by Shawn4easy** [comment]
@jszobody Do you have rules for contributors?

**Comment by jszobody** [comment]
@Shawn4easy we don't have set rules, no. generally: submit clean/organized code, and we typically merge it in!

On a side note: I'm curious if you all have looked at Laravel Pint (https://laravel.com/docs/9.x/pint) and if there is a reason to still keep this package around? Our own team hasn't been using this package a whole lot lately. Now that there is an official Laravel wrapper for CS Fixer, we're not sure if it's worth maintaining this one any longer. Would it be possible for the folks in this thread to switch to Pint, or would that be problematic?
